#setup parameters
Date_Ticks: multi_year
EPIC_Key: 
#- ICEC_2025
- T_20
- T_25
Ylabel: SST
MooringID: "M2_HROISSTV2"
output_type: png
plot_stylesheet: seaborn-poster
EPIC_Key_ctd: T_28
ctd_data_path:
- ''
ctd_files:
- ''
dtype: ''
legend:
- ''
legend_loc: upper center
legend_off: true
colors:
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
#start mooring data
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
#- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
- b-
mooring_data_path:
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
#- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/ecoraid/2016/Moorings/16bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2015/Moorings/15bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2015/Moorings/15bs2c/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2014/Moorings/14bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2014/Moorings/14bs2c/working/
- /Volumes/WDC_internal/Users/bell/ecoraid/2013/Moorings/13bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2013/Moorings/13bs2c/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2012/Moorings/12bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2012/Moorings/12bs2c/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2011/Moorings/11bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2011/Moorings/11bs2c/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2010/Moorings/10bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2010/Moorings/10bs2c/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2009/Moorings/09bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2008/Moorings/08bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2008/Moorings/08bs2c/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2007/Moorings/07bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2007/Moorings/07bs2c/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2006/Moorings/06bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2006/Moorings/06bs2c/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2005/Moorings/05bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2005/Moorings/05bs2c/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2004/Moorings/04bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2004/Moorings/04bs2c/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2003/Moorings/03bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2003/Moorings/03bs2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2003/Moorings/03bs2c/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2002/Moorings/02bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2002/Moorings/02bs2c/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2001/Moorings/01bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2001/Moorings/01bs2b/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2001/Moorings/01bs2c/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2000/Moorings/00bsm2a/final_data/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2000/Moorings/00bs2a/final_data/
mooring_files:
#- NOAA_OI_SST_V2_M2_2000.nc
#- NOAA_OI_SST_V2_M2_2001.nc
#- NOAA_OI_SST_V2_M2_2002.nc
#- NOAA_OI_SST_V2_M2_2003.nc
#- NOAA_OI_SST_V2_M2_2004.nc
#- NOAA_OI_SST_V2_M2_2005.nc
#- NOAA_OI_SST_V2_M2_2006.nc
#- NOAA_OI_SST_V2_M2_2007.nc
#- NOAA_OI_SST_V2_M2_2008.nc
#- NOAA_OI_SST_V2_M2_2009.nc
#- NOAA_OI_SST_V2_M2_2010.nc
#- NOAA_OI_SST_V2_M2_2011.nc
#- NOAA_OI_SST_V2_M2_2012.nc
#- NOAA_OI_SST_V2_M2_2013.nc
#- NOAA_OI_SST_V2_M2_2014.nc
#- NOAA_OI_SST_V2_M2_2015.nc
#- NOAA_OI_SST_V2_M2_2016.nc
#- 16bsm2a_mt3276_0004m.nc
#- 15bsm2a_mt4004_0004m.nc
#- 15bs2c_sc_0012m.nc
#- 14bsm2a_mt4016_0004m.nc
#- 14bs2c_sc_0012m.unqcd.interpolated.trimmed_missing.nc
#- 13bsm2a_mt_0004m.nc
#- 13bs2c_sc_0012m.nc
#- 12bsm2a_s37_0001m.nc
#- 12bs2c_sc_0011m.nc
#- 11bsm2a_mt_0004m.nc
#- 11bs2c_sc_0012m.nc
#- 10bsm2a_s37_0001m.nc
#- 10bs2c_sc_0010m.nc
#- 09bsm2a_s37_0001m.nc
##- no shallow 09bs2c 
#- 08bsm2a_s37_0001m.nc
#- 08bs2c_sc_0010m.nc
#- 07bsm2a_s37_0001m.nc
#- 07bs2c_sc_0009m.nc
#- 06bsm2a_s37_0001m.nc
#- 06bs2c_sc_0010m.nc
#- 05bsm2a_sc_0001m.nc
#- 05bs2c_sc_0010m.nc
#- 04bsm2a_sc_0001m.nc
#- 04bs2c_s37_0011m.nc
#- 03bsm2a_sc_0001m.nc
#- 03bs2a_sc_0011m.nc
#- 03bs2c_sc_0011m.nc
#- 02bsm2a_sc_0001m.nc
#- 02bs2c_sc_0011m.nc
#- 01bsm2a_sc_0001m.nc
#- 01bs2b_sc_0013m.nc
#- 01bs2c_sc_0006m.nc
#- 00bsm2a_sc_0001m.nc
#- 00bs2a_sc_0007m.nc
- 16bsm2a_mt3276_0004m.nc
- 15bsm2a_mt4004_0004m.nc
- 15bs2c_sc_0012m.nc
- 14bsm2a_mt4016_0004m.nc
- 14bs2c_sc_0012m.unqcd.interpolated.trimmed_missing.nc
- 13bsm2a_mt_0004m.nc
- 13bs2c_sc_0012m.nc
- 12bsm2a_s37_0001m.nc
- 12bs2c_sc_0011m.nc
- 11bsm2a_mt_0004m.nc
- 11bs2c_sc_0012m.nc
- 10bsm2a_s37_0001m.nc
- 10bs2c_sc_0010m.nc
- 09bsm2a_s37_0001m.nc
#- no shallow 09bs2c 
- 08bsm2a_s37_0001m.nc
- 08bs2c_sc_0010m.nc
- 07bsm2a_s37_0001m.nc
- 07bs2c_sc_0009m.nc
- 06bsm2a_s37_0001m.nc
- 06bs2c_sc_0010m.nc
- 05bsm2a_sc_0001m.nc
- 05bs2c_sc_0010m.nc
- 04bsm2a_sc_0001m.nc
- 04bs2c_s37_0011m.nc
- 03bsm2a_sc_0001m.nc
- 03bs2a_sc_0031m.nc
- 03bs2c_sc_0011m.nc
- 02bsm2a_sc_0001m.nc
- 02bs2c_s39_0021m.nc
- 01bsm2a_sc_0001m.nc
- 01bs2b_mt_0020m.nc
- 01bs2c_s39_0024m.nc
- 00bsm2a_sc_0001m.nc
#- 00bs2a_sc_0007m.nc
legend:
- 2000 sst
- 2001 sst
- 2002 sst
- 2003 sst
- 2004 sst
- 2005 sst
- 2006 sst
- 2007 sst
- 2008 sst
- 2009 sst
- 2010 sst
- 2011 sst
- 2012 sst
- 2013 sst
- 2014 sst
- 2015 sst
- 2016 sst
- 2016
- 2015
- 2015
- 2014
- 2014
- 2013
- 2013
- 2012
- 2012
- 2011
- 2011
- 2010
- 2010
- 2009
- 2008
- 2008
- 2007
- 2007
- 2006
- 2006
- 2005
- 2005
- 2004
- 2004
- 2003
- 2003
- 2003
- 2002
- 2002
- 2001
- 2001
- 2001
- 2000
- 2000