#setup parameters
Date_Ticks: multi_year
EPIC_Key: 
- T_25
- T_20
Ylabel: SST
MooringID: "M2_HROISSTV2"
output_type: png
plot_stylesheet: seaborn-poster
EPIC_Key_ctd: T_28
ctd_data_path:
- ''
ctd_files:
- ''
dtype: ''
legend:
- ''
legend_loc: upper center
legend_off: true
colors:
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- r-
- r-
- r-
- r-
- r-
- r-
- r-
- r-
- r-
- r-
- r-
mooring_data_path:
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M2_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/ecoraid/2016/Moorings/16bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2015/Moorings/15bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2014/Moorings/14bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2013/Moorings/13bsm2a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2012/Moorings/12bsm2a/final_data/
mooring_files:
- NOAA_OI_SST_V2_M2_2000.nc
- NOAA_OI_SST_V2_M2_2001.nc
- NOAA_OI_SST_V2_M2_2002.nc
- NOAA_OI_SST_V2_M2_2003.nc
- NOAA_OI_SST_V2_M2_2004.nc
- NOAA_OI_SST_V2_M2_2005.nc
- NOAA_OI_SST_V2_M2_2006.nc
- NOAA_OI_SST_V2_M2_2007.nc
- NOAA_OI_SST_V2_M2_2008.nc
- NOAA_OI_SST_V2_M2_2009.nc
- NOAA_OI_SST_V2_M2_2010.nc
- NOAA_OI_SST_V2_M2_2011.nc
- NOAA_OI_SST_V2_M2_2012.nc
- NOAA_OI_SST_V2_M2_2013.nc
- NOAA_OI_SST_V2_M2_2014.nc
- NOAA_OI_SST_V2_M2_2015.nc
- NOAA_OI_SST_V2_M2_2016.nc
- 16bsm2a_mt3276_0004m.nc
- 15bsm2a_mt4004_0004m.nc
- 14bsm2a_mt4016_0004m.nc
- 13bsm2a_mt_0004m.nc
- 12bsm2a_s37_0001m.nc
legend:
- 2000 sst
- 2001 sst
- 2002 sst
- 2003 sst
- 2004 sst
- 2005 sst
- 2006 sst
- 2007 sst
- 2008 sst
- 2009 sst
- 2010 sst
- 2011 sst
- 2012 sst
- 2013 sst
- 2014 sst
- 2015 sst
- 2016 sst
- 2016
- 2015
- 2014
- 2013
- 2012