#setup parameters
Date_Ticks: multi_year
EPIC_Key: 
- T_25
- T_20
Ylabel: SST
MooringID: "M8_HROISSTV2"
output_type: png
plot_stylesheet: seaborn-poster
EPIC_Key_ctd: T_28
ctd_data_path:
- ''
ctd_files:
- ''
dtype: ''
legend:
- ''
legend_loc: upper center
legend_off: true
colors:
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- r-
- r-
- r-
- r-
- r-
- r-
- r-
- r-
- r-
- r-
- r-
- r-
mooring_data_path:
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/
- /Volumes/WDC_internal/Users/bell/ecoraid/2015/Moorings/15bs8a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2014/Moorings/14bs8a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2013/Moorings/13bs8a/working/
- /Volumes/WDC_internal/Users/bell/ecoraid/2012/Moorings/12bs8a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2011/Moorings/11bs8a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2010/Moorings/10bs8a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2009/Moorings/09bsv8a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2009/Moorings/09bs8a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2008/Moorings/08bsv8a/final_data/
- /Volumes/WDC_internal/Users/bell/ecoraid/2008/Moorings/08bs8a/final_data/
mooring_files:
- NOAA_OI_SST_V2_M8_2000.nc
- NOAA_OI_SST_V2_M8_2001.nc
- NOAA_OI_SST_V2_M8_2002.nc
- NOAA_OI_SST_V2_M8_2003.nc
- NOAA_OI_SST_V2_M8_2004.nc
- NOAA_OI_SST_V2_M8_2005.nc
- NOAA_OI_SST_V2_M8_2006.nc
- NOAA_OI_SST_V2_M8_2007.nc
- NOAA_OI_SST_V2_M8_2008.nc
- NOAA_OI_SST_V2_M8_2009.nc
- NOAA_OI_SST_V2_M8_2010.nc
- NOAA_OI_SST_V2_M8_2011.nc
- NOAA_OI_SST_V2_M8_2012.nc
- NOAA_OI_SST_V2_M8_2013.nc
- NOAA_OI_SST_V2_M8_2014.nc
- NOAA_OI_SST_V2_M8_2015.nc
- NOAA_OI_SST_V2_M8_2016.nc
- 15bs8a_s39_0023m.nc
- 14bs8a_s39_0027m.nc
- 13bs8a_sc_0021m.unqcd.trimmed_missing.nc
- 12bs8a_sc_0021m.nc
- 11bs8a_sc_0021m.nc
- 10bs8a_sc_0021m.nc
- 09bsv8a_s39_0005m.nc
- 09bs8a_sc_0021m.nc
- 08bsv8a_s39_0005m.nc
- 08bs8a_sc_0021m.nc 
legend:
- 2000 sst
- 2001 sst
- 2002 sst
- 2003 sst
- 2004 sst
- 2005 sst
- 2006 sst
- 2007 sst
- 2008 sst
- 2009 sst
- 2010 sst
- 2011 sst
- 2012 sst
- 2013 sst
- 2014 sst
- 2015 sst
- 2016 sst
- 2015
- 2014
- 2013
- 2012
- 2011
- 2010
- 2009
- 2009
- 2008
- 2008