#setup parameters
Date_Ticks: multi_year
EPIC_Key: 
- ICEC_2025
#- T_20
#- T_25
Ylabel: SST
MooringID: "M8_HROISSTV2"
output_type: png
plot_stylesheet: seaborn-poster
EPIC_Key_ctd: T_28
ctd_data_path:
- ''
ctd_files:
- ''
dtype: ''
legend:
- ''
legend_loc: upper center
legend_off: true
colors:
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
- k-
# start mooring
- b-
- b-
- b-
- b-
- b-
- b-
- r-
- b-
- r-
- b-
- b-
- b-
- b-
- b-
mooring_data_path:
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
- /Volumes/WDC_internal/Users/bell/Data_Local/sst/M8_NOAA_OI_SST_V2/epic_conventions/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2015/Moorings/15bs8a/final_data/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2014/Moorings/14bs8a/final_data/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2013/Moorings/13bs8a/working/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2012/Moorings/12bs8a/final_data/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2011/Moorings/11bs8a/final_data/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2010/Moorings/10bs8a/final_data/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2009/Moorings/09bsv8a/final_data/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2009/Moorings/09bs8a/final_data/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2008/Moorings/08bsv8a/final_data/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2008/Moorings/08bs8a/final_data/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2007/Moorings/07bs8a/final_data/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2006/Moorings/06bs8a/final_data/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2005/Moorings/05bs8a/final_data/
#- /Volumes/WDC_internal/Users/bell/ecoraid/2005/Moorings/05bs8b/final_data/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
#- /Volumes/WDC_internal/Users/bell/in_and_outbox/2017/stabeno/jan/M2_M8_SSTTemp_analysis/mooringdata/M8/
mooring_files:
- NOAA_OI_SST_V2_M8_2004.nc
- NOAA_OI_SST_V2_M8_2005.nc
- NOAA_OI_SST_V2_M8_2006.nc
- NOAA_OI_SST_V2_M8_2007.nc
- NOAA_OI_SST_V2_M8_2008.nc
- NOAA_OI_SST_V2_M8_2009.nc
- NOAA_OI_SST_V2_M8_2010.nc
- NOAA_OI_SST_V2_M8_2011.nc
- NOAA_OI_SST_V2_M8_2012.nc
- NOAA_OI_SST_V2_M8_2013.nc
- NOAA_OI_SST_V2_M8_2014.nc
- NOAA_OI_SST_V2_M8_2015.nc
- NOAA_OI_SST_V2_M8_2016.nc
- NOAA_OI_SST_V2_M8_2017.nc
#- 15bs8a_s39_0023m.nc
#- 14bs8a_s39_0023m.nc
#- 13bs8a_sc_0021m.unqcd.trimmed_missing.nc
#- 12bs8a_sc_0021m.nc
#- 11bs8a_sc_0021m.nc
#- 10bs8a_sc_0021m.nc
#- 09bsv8a_s39_0005m.nc
#- 09bs8a_sc_0021m.nc
#- 08bsv8a_s39_0005m.nc
#- 08bs8a_sc_0021m.nc 
#- 07bs8a_sc_0021m.nc
#- 06bs8a_sc_0022m.nc
#- 05bs8a_sc_0014m.nc
#- 05bs8b_sc_0021m.nc
#- 15bs8a_s39_0023m_f35.nc
#- 14bs8a_s39_0023m_f35.nc
#- 13bs8a_sc_0021m_f35.nc
#- 12bs8a_sc_0021m_f35.nc
#- 11bs8a_sc_0021m_f35.nc
#- 10bs8a_sc_0021m_f35.nc
##- 09bsv8a_s39_0005m_f35.nc
#- 09bs8a_sc_0021m_f35.nc
##- 08bsv8a_s39_0005m_f35.nc
#- 08bs8a_sc_0021m_f35.nc 
#- 07bs8a_sc_0021m_f35.nc
#- 06bs8a_sc_0022m_f35.nc
#- 05bs8a_sc_0014m_f35.nc
#- 05bs8b_sc_0021m_f35.nc
legend:
- 2004 sst
- 2005 sst
- 2006 sst
- 2007 sst
- 2008 sst
- 2009 sst
- 2010 sst
- 2011 sst
- 2012 sst
- 2013 sst
- 2014 sst
- 2015 sst
- 2016 sst
- 2017 sst
- 2015 23m
- 2014 27m
- 2013 21m
- 2012 21m
- 2011 21m
- 2010 21m
- 2009 *5m
- 2009 21m
- 2008 *5m
- 2008 21m
- 2007 21m 
- 2006 22m
- 2005 14m
- 2005 21mm